### ISSUE TITLE
which python pil version do i need to run this?

### ISSUE THREAD

**Issue by 0xh3LL0** [ningshanwutuobang/ChaosChildPCTools#2]
at the moment i'm using python 3.4 with pillow 5.4.1 (latest that i found) but it refuse to run
![py](https://user-images.githubusercontent.com/23132217/53312992-fd512600-38e9-11e9-87d6-96181771e6fd.PNG)

and even though its not chaos child, can you take a look if your tools work with this or not?
[chara.zip](https://github.com/ningshanwutuobang/ChaosChildPCTools/files/2898946/chara.zip)

**Comment by ningshanwutuobang** [comment]
For .gxt files, I advice you to use https://github.com/xdanieldzd/GXTConvert. 


My version is incomplete. And the I'm using python3.6 with pillow 5.4.1. I think you didn't install Pillow completely, you should check the installation. 
The format is similar. The main structure is (x,y,u,v) for (x,y) in display and (u,v) in image. 

I add a test.py file for the  layout file.
[test_py.zip](https://github.com/ningshanwutuobang/ChaosChildPCTools/files/3013257/test_py.zip)
@0xh3LL0

**Comment by 0xh3LL0** [comment]
thank you very much!
guess i'll update my python.
