### ISSUE TITLE
关于mvl中的f2int函数

### ISSUE THREAD

**Issue by wetor** [ningshanwutuobang/ChaosChildPCTools#3]
yu-no的立绘用四舍五入会导致部分mvl出现缝隙(竖线)，直接取整没问题，是存在不用四舍五入就会出问题的mvl吗？
顺便感谢楼主的lay和mvl脚本

**Comment by ningshanwutuobang** [comment]
我主要测试了Chaos;Child Love chu☆chu!，不用四舍五入会出问题。
[HAI_AXC.zip](https://github.com/ningshanwutuobang/ChaosChildPCTools/files/3102818/HAI_AXC.zip)
@wetor

**Comment by wetor** [comment]
[ync_chi_sac.zip](https://github.com/ningshanwutuobang/ChaosChildPCTools/files/3102842/ync_chi_sac.zip)
NS版yuno的CG

**Comment by ningshanwutuobang** [comment]
问题应该出在对负数的处理。

**Comment by ningshanwutuobang** [comment]
我去掉了缩放的整除部分，结果应该会好一些。
@wetor

**Comment by wetor** [comment]
OK,那我也不测试了，只要我发的那个没问题，大概就都不会有什么问题了吧
